### ISSUE TITLE
I can't seem to get openwrt to be put on my wr703n ver 1.7

### ISSUE THREAD

**Issue by nullnek0** [nneves/TL-WR703N_OpenWrt_LibCurl#1]
I can't seem to get openwrt to be put on my wr703n ver 1.7 I've looked everywhere done everything it just won't work I was hoping you could help

Thankyou

**Comment by nelsonsneves** [comment]
Sorry, I've done this a long time ago, not easy to get it to work!
I will not be able to assist you at the moment, currently busy with work, sorry!

**Comment by nneves** [comment]
Sorry, I've done this a long time ago, not easy to get it to work!
I will not be able to assist you at the moment, currently busy with work, sorry!
